name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build APK with Buildozer
      uses: kivy/buildozer-action@v1
      with:
        command: buildozer android debug
        submodule_update: false

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SB_INFOTECH_Android_APK
        path: bin/*.apk
